import type { Team, Weights } from "./types";

export const dataSnapshot = {
  date: "2026-07-04",
  label: "openfootball/worldcup 2026--usa 真实赛程快照",
  note: "分组、小组赛赛果、最终小组积分和 32 强赛果按 openfootball/worldcup 的 2026--usa/cup.txt 与 cup_finals.txt 核对；16 强及后续尚未填入比分的场次继续由模型预测。",
};

export type TeamCode = (typeof teams)[number]["code"];

export type GroupTableRow = {
  code: Team["code"];
  played: number;
  wins: number;
  draws: number;
  losses: number;
  points: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  status: "qualified" | "thirdQualified" | "eliminated";
};

export type KnockoutFixture = {
  id: string;
  round: "R32" | "R16" | "QF" | "SF" | "F";
  slot: string;
  home: Team["code"];
  away: Team["code"];
  status: "actual" | "forecast";
  homeGoals?: number;
  awayGoals?: number;
  winner?: Team["code"];
  scoreNote?: string;
};

export const defaultWeights: Weights = {
  strength: 34,
  form: 22,
  depth: 18,
  knockout: 16,
  travel: 10,
};

export const teams: Team[] = [
  {
    code: "MEX",
    name: "墨西哥",
    group: "A",
    confederation: "CONCACAF",
    rank: 15,
    strength: 84,
    form: 83,
    depth: 77,
    knockout: 76,
    travel: 96,
    attack: 80,
    defense: 78,
    note: "东道主之一，小组赛三连胜且零封，主场适应和比赛节奏管理是核心优势。",
  },
  {
    code: "RSA",
    name: "南非",
    group: "A",
    confederation: "CAF",
    rank: 54,
    strength: 67,
    form: 70,
    depth: 60,
    knockout: 57,
    travel: 69,
    attack: 62,
    defense: 65,
    note: "小组第二晋级，防守韧性和定位球质量是淘汰赛中的主要变量。",
  },
  {
    code: "CZE",
    name: "捷克",
    group: "A",
    confederation: "UEFA",
    rank: 40,
    strength: 72,
    form: 63,
    depth: 68,
    knockout: 65,
    travel: 60,
    attack: 69,
    defense: 72,
    note: "欧洲中游强队，身体对抗不差，但本届小组阶段效率不足。",
  },
  {
    code: "KOR",
    name: "韩国",
    group: "A",
    confederation: "AFC",
    rank: 23,
    strength: 77,
    form: 71,
    depth: 71,
    knockout: 65,
    travel: 59,
    attack: 74,
    defense: 72,
    note: "转换速度和边路推进有威胁，但小组赛稳定性低于模型预期。",
  },
  {
    code: "CAN",
    name: "加拿大",
    group: "B",
    confederation: "CONCACAF",
    rank: 31,
    strength: 77,
    form: 81,
    depth: 70,
    knockout: 62,
    travel: 97,
    attack: 80,
    defense: 70,
    note: "东道主之一，已经取得队史淘汰赛突破，速度与场地适应明显加分。",
  },
  {
    code: "BIH",
    name: "波黑",
    group: "B",
    confederation: "UEFA",
    rank: 36,
    strength: 73,
    form: 68,
    depth: 69,
    knockout: 60,
    travel: 61,
    attack: 72,
    defense: 69,
    note: "技术型中前场具备创造力，但面对高压球队时防线空间管理是风险。",
  },
  {
    code: "QAT",
    name: "卡塔尔",
    group: "B",
    confederation: "AFC",
    rank: 35,
    strength: 68,
    form: 66,
    depth: 62,
    knockout: 57,
    travel: 56,
    attack: 64,
    defense: 65,
    note: "亚洲杯经验有帮助，但面对高节奏强队时防守压力偏大。",
  },
  {
    code: "SUI",
    name: "瑞士",
    group: "B",
    confederation: "UEFA",
    rank: 18,
    strength: 82,
    form: 78,
    depth: 79,
    knockout: 77,
    travel: 63,
    attack: 76,
    defense: 80,
    note: "大赛稳定性强，防守纪律和中场控制通常能提高淘汰赛下限。",
  },
  {
    code: "BRA",
    name: "巴西",
    group: "C",
    confederation: "CONMEBOL",
    rank: 5,
    strength: 92,
    form: 84,
    depth: 92,
    knockout: 90,
    travel: 66,
    attack: 93,
    defense: 84,
    note: "进攻天赋和阵容厚度仍是第一梯队，模型担忧点是防守波动。",
  },
  {
    code: "HAI",
    name: "海地",
    group: "C",
    confederation: "CONCACAF",
    rank: 86,
    strength: 58,
    form: 60,
    depth: 52,
    knockout: 44,
    travel: 80,
    attack: 57,
    defense: 58,
    note: "速度和身体冲击有亮点，但整体阵容深度与强队差距明显。",
  },
  {
    code: "MAR",
    name: "摩洛哥",
    group: "C",
    confederation: "CAF",
    rank: 12,
    strength: 85,
    form: 84,
    depth: 78,
    knockout: 83,
    travel: 64,
    attack: 79,
    defense: 85,
    note: "防守结构和转换效率延续高水准，具备连续淘汰赛竞争力。",
  },
  {
    code: "SCO",
    name: "苏格兰",
    group: "C",
    confederation: "UEFA",
    rank: 33,
    strength: 73,
    form: 69,
    depth: 67,
    knockout: 61,
    travel: 60,
    attack: 68,
    defense: 72,
    note: "对抗强度高，适合低比分缠斗，进攻转化率决定上限。",
  },
  {
    code: "USA",
    name: "美国",
    group: "D",
    confederation: "CONCACAF",
    rank: 11,
    strength: 85,
    form: 82,
    depth: 81,
    knockout: 70,
    travel: 98,
    attack: 83,
    defense: 78,
    note: "东道主红利和年轻阵容速度明显，淘汰赛经验仍是折扣项。",
  },
  {
    code: "PAR",
    name: "巴拉圭",
    group: "D",
    confederation: "CONMEBOL",
    rank: 39,
    strength: 75,
    form: 78,
    depth: 70,
    knockout: 72,
    travel: 73,
    attack: 71,
    defense: 76,
    note: "南美对抗质量和点球心理抗压加分，适合淘汰赛低比分场景。",
  },
  {
    code: "AUS",
    name: "澳大利亚",
    group: "D",
    confederation: "AFC",
    rank: 27,
    strength: 72,
    form: 73,
    depth: 66,
    knockout: 67,
    travel: 55,
    attack: 68,
    defense: 73,
    note: "身体对抗和纪律性强，赛程密集时体能管理是关键。",
  },
  {
    code: "TUR",
    name: "土耳其",
    group: "D",
    confederation: "UEFA",
    rank: 22,
    strength: 79,
    form: 80,
    depth: 75,
    knockout: 70,
    travel: 60,
    attack: 80,
    defense: 72,
    note: "年轻核心活力强，进攻创造力足，防守波动带来不确定性。",
  },
  {
    code: "GER",
    name: "德国",
    group: "E",
    confederation: "UEFA",
    rank: 4,
    strength: 90,
    form: 86,
    depth: 91,
    knockout: 92,
    travel: 61,
    attack: 89,
    defense: 83,
    note: "中前场人才密度极高，淘汰赛执行力使其保持冠军级威胁。",
  },
  {
    code: "CUW",
    name: "库拉索",
    group: "E",
    confederation: "CONCACAF",
    rank: 75,
    strength: 60,
    form: 63,
    depth: 55,
    knockout: 48,
    travel: 78,
    attack: 58,
    defense: 60,
    note: "首次大赛级别经验有限，模型主要看其防守组织和反击效率。",
  },
  {
    code: "CIV",
    name: "科特迪瓦",
    group: "E",
    confederation: "CAF",
    rank: 38,
    strength: 74,
    form: 76,
    depth: 71,
    knockout: 67,
    travel: 63,
    attack: 75,
    defense: 70,
    note: "身体对抗和边路突击有竞争力，面对强队时转换质量很关键。",
  },
  {
    code: "ECU",
    name: "厄瓜多尔",
    group: "E",
    confederation: "CONMEBOL",
    rank: 26,
    strength: 78,
    form: 76,
    depth: 71,
    knockout: 64,
    travel: 72,
    attack: 74,
    defense: 76,
    note: "南美对抗强度和年轻球员冲击力加分，具备爆冷能力。",
  },
  {
    code: "NED",
    name: "荷兰",
    group: "F",
    confederation: "UEFA",
    rank: 7,
    strength: 89,
    form: 84,
    depth: 85,
    knockout: 88,
    travel: 61,
    attack: 85,
    defense: 88,
    note: "中后场质量和淘汰赛经验优秀，锋线效率稳定则有四强潜力。",
  },
  {
    code: "JPN",
    name: "日本",
    group: "F",
    confederation: "AFC",
    rank: 16,
    strength: 84,
    form: 85,
    depth: 80,
    knockout: 73,
    travel: 58,
    attack: 82,
    defense: 78,
    note: "高压和控传体系成熟，具备连续爆冷能力。",
  },
  {
    code: "SWE",
    name: "瑞典",
    group: "F",
    confederation: "UEFA",
    rank: 24,
    strength: 77,
    form: 71,
    depth: 72,
    knockout: 70,
    travel: 59,
    attack: 74,
    defense: 76,
    note: "传统高空优势和防守纪律仍在，创造力决定能走多远。",
  },
  {
    code: "TUN",
    name: "突尼斯",
    group: "F",
    confederation: "CAF",
    rank: 41,
    strength: 68,
    form: 66,
    depth: 61,
    knockout: 57,
    travel: 63,
    attack: 62,
    defense: 69,
    note: "低位防守有组织性，面对强队时需要早段守住比分。",
  },
  {
    code: "BEL",
    name: "比利时",
    group: "G",
    confederation: "UEFA",
    rank: 8,
    strength: 88,
    form: 83,
    depth: 83,
    knockout: 81,
    travel: 61,
    attack: 87,
    defense: 79,
    note: "过渡期后仍具备高质量前场，逆转塞内加尔提升模型状态分。",
  },
  {
    code: "EGY",
    name: "埃及",
    group: "G",
    confederation: "CAF",
    rank: 32,
    strength: 74,
    form: 72,
    depth: 67,
    knockout: 66,
    travel: 61,
    attack: 76,
    defense: 70,
    note: "前场个人能力强，小组出线取决于防守转换和核心健康。",
  },
  {
    code: "IRN",
    name: "伊朗",
    group: "G",
    confederation: "AFC",
    rank: 20,
    strength: 76,
    form: 75,
    depth: 69,
    knockout: 60,
    travel: 58,
    attack: 72,
    defense: 73,
    note: "亚洲强队，防守和定位球稳定，小组赛抗压能力较强。",
  },
  {
    code: "NZL",
    name: "新西兰",
    group: "G",
    confederation: "OFC",
    rank: 88,
    strength: 59,
    form: 58,
    depth: 52,
    knockout: 48,
    travel: 50,
    attack: 55,
    defense: 57,
    note: "身体条件不差，但整体比赛强度和阵容厚度差距较大。",
  },
  {
    code: "ESP",
    name: "西班牙",
    group: "H",
    confederation: "UEFA",
    rank: 3,
    strength: 92,
    form: 90,
    depth: 90,
    knockout: 89,
    travel: 61,
    attack: 89,
    defense: 86,
    note: "控球、压迫和年轻化红利明显，若进攻效率稳定就是冠军级。",
  },
  {
    code: "CPV",
    name: "佛得角",
    group: "H",
    confederation: "CAF",
    rank: 65,
    strength: 63,
    form: 70,
    depth: 58,
    knockout: 50,
    travel: 64,
    attack: 62,
    defense: 60,
    note: "突破性参赛提升士气，强项在团队纪律和反击执行。",
  },
  {
    code: "KSA",
    name: "沙特",
    group: "H",
    confederation: "AFC",
    rank: 57,
    strength: 64,
    form: 62,
    depth: 59,
    knockout: 55,
    travel: 57,
    attack: 61,
    defense: 62,
    note: "具备单场爆冷基因，但连续高强度赛程下稳定性不足。",
  },
  {
    code: "URU",
    name: "乌拉圭",
    group: "H",
    confederation: "CONMEBOL",
    rank: 10,
    strength: 86,
    form: 84,
    depth: 80,
    knockout: 86,
    travel: 72,
    attack: 84,
    defense: 83,
    note: "侵略性、淘汰赛气质和南美对抗强度兼具。",
  },
  {
    code: "FRA",
    name: "法国",
    group: "I",
    confederation: "UEFA",
    rank: 2,
    strength: 94,
    form: 89,
    depth: 95,
    knockout: 94,
    travel: 62,
    attack: 93,
    defense: 87,
    note: "阵容深度和锋线速度冠绝多数对手，是模型给出的最高冠军概率球队。",
  },
  {
    code: "SEN",
    name: "塞内加尔",
    group: "I",
    confederation: "CAF",
    rank: 19,
    strength: 80,
    form: 79,
    depth: 74,
    knockout: 72,
    travel: 62,
    attack: 77,
    defense: 80,
    note: "身体素质、防守质量和反击速度均衡，是很难对付的球队。",
  },
  {
    code: "IRQ",
    name: "伊拉克",
    group: "I",
    confederation: "AFC",
    rank: 56,
    strength: 64,
    form: 66,
    depth: 60,
    knockout: 53,
    travel: 56,
    attack: 61,
    defense: 63,
    note: "团队纪律不错，面对强队时依赖低位防守和反击效率。",
  },
  {
    code: "NOR",
    name: "挪威",
    group: "I",
    confederation: "UEFA",
    rank: 28,
    strength: 81,
    form: 84,
    depth: 76,
    knockout: 65,
    travel: 58,
    attack: 84,
    defense: 72,
    note: "锋线终结能力突出，淘汰赛中进球效率是最大加分项。",
  },
  {
    code: "ARG",
    name: "阿根廷",
    group: "J",
    confederation: "CONMEBOL",
    rank: 1,
    strength: 93,
    form: 90,
    depth: 88,
    knockout: 96,
    travel: 69,
    attack: 90,
    defense: 86,
    note: "卫冕冠军的稳定心态、淘汰赛经验和中场控制使其仍是夺冠热门。",
  },
  {
    code: "ALG",
    name: "阿尔及利亚",
    group: "J",
    confederation: "CAF",
    rank: 36,
    strength: 74,
    form: 72,
    depth: 69,
    knockout: 65,
    travel: 63,
    attack: 75,
    defense: 69,
    note: "前场技术与转换速度不错，稳定性决定能否冲击出线。",
  },
  {
    code: "AUT",
    name: "奥地利",
    group: "J",
    confederation: "UEFA",
    rank: 25,
    strength: 78,
    form: 79,
    depth: 73,
    knockout: 68,
    travel: 60,
    attack: 77,
    defense: 74,
    note: "高压体系成熟，整体纪律好，但面对冠军级球队时火力不足。",
  },
  {
    code: "JOR",
    name: "约旦",
    group: "J",
    confederation: "AFC",
    rank: 68,
    strength: 61,
    form: 66,
    depth: 56,
    knockout: 49,
    travel: 55,
    attack: 60,
    defense: 58,
    note: "突破性参赛提升信心，主要依赖团队纪律和反击效率。",
  },
  {
    code: "POR",
    name: "葡萄牙",
    group: "K",
    confederation: "UEFA",
    rank: 6,
    strength: 90,
    form: 87,
    depth: 93,
    knockout: 87,
    travel: 62,
    attack: 91,
    defense: 83,
    note: "前场和边路人才密度极高，深度足以支撑长赛程。",
  },
  {
    code: "COD",
    name: "民主刚果",
    group: "K",
    confederation: "CAF",
    rank: 60,
    strength: 66,
    form: 70,
    depth: 62,
    knockout: 56,
    travel: 63,
    attack: 68,
    defense: 62,
    note: "身体对抗强，反击有冲击力，但防线组织稳定性有限。",
  },
  {
    code: "UZB",
    name: "乌兹别克斯坦",
    group: "K",
    confederation: "AFC",
    rank: 55,
    strength: 65,
    form: 70,
    depth: 62,
    knockout: 52,
    travel: 54,
    attack: 64,
    defense: 62,
    note: "技术和团队纪律近年提升，首次大舞台经验是变量。",
  },
  {
    code: "COL",
    name: "哥伦比亚",
    group: "K",
    confederation: "CONMEBOL",
    rank: 13,
    strength: 84,
    form: 85,
    depth: 78,
    knockout: 74,
    travel: 75,
    attack: 82,
    defense: 78,
    note: "近期状态和南美对抗强度加分，具备进入八强的质量。",
  },
  {
    code: "ENG",
    name: "英格兰",
    group: "L",
    confederation: "UEFA",
    rank: 4,
    strength: 91,
    form: 86,
    depth: 92,
    knockout: 85,
    travel: 60,
    attack: 90,
    defense: 84,
    note: "阵容深度和定位球质量极高，模型对关键战临场保守度做折扣。",
  },
  {
    code: "CRO",
    name: "克罗地亚",
    group: "L",
    confederation: "UEFA",
    rank: 15,
    strength: 82,
    form: 77,
    depth: 75,
    knockout: 91,
    travel: 60,
    attack: 76,
    defense: 81,
    note: "淘汰赛经验巨大加分，但年龄结构和强度延续性是风险。",
  },
  {
    code: "GHA",
    name: "加纳",
    group: "L",
    confederation: "CAF",
    rank: 47,
    strength: 70,
    form: 68,
    depth: 66,
    knockout: 62,
    travel: 62,
    attack: 70,
    defense: 66,
    note: "冲击力强但稳定性不足，小组赛和淘汰赛都需要控制失误率。",
  },
  {
    code: "PAN",
    name: "巴拿马",
    group: "L",
    confederation: "CONCACAF",
    rank: 45,
    strength: 68,
    form: 69,
    depth: 61,
    knockout: 54,
    travel: 82,
    attack: 65,
    defense: 66,
    note: "区域适应好，强对抗下仍需提升控球出球。",
  },
];

export const groupTables: Record<string, GroupTableRow[]> = {
  A: [
    { code: "MEX", played: 3, wins: 3, draws: 0, losses: 0, points: 9, goalsFor: 6, goalsAgainst: 0, goalDifference: 6, status: "qualified" },
    { code: "RSA", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 2, goalsAgainst: 3, goalDifference: -1, status: "qualified" },
    { code: "KOR", played: 3, wins: 1, draws: 0, losses: 2, points: 3, goalsFor: 2, goalsAgainst: 3, goalDifference: -1, status: "eliminated" },
    { code: "CZE", played: 3, wins: 0, draws: 1, losses: 2, points: 1, goalsFor: 2, goalsAgainst: 6, goalDifference: -4, status: "eliminated" },
  ],
  B: [
    { code: "SUI", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 7, goalsAgainst: 3, goalDifference: 4, status: "qualified" },
    { code: "CAN", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 8, goalsAgainst: 3, goalDifference: 5, status: "qualified" },
    { code: "BIH", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 5, goalsAgainst: 6, goalDifference: -1, status: "thirdQualified" },
    { code: "QAT", played: 3, wins: 0, draws: 1, losses: 2, points: 1, goalsFor: 2, goalsAgainst: 10, goalDifference: -8, status: "eliminated" },
  ],
  C: [
    { code: "BRA", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 7, goalsAgainst: 1, goalDifference: 6, status: "qualified" },
    { code: "MAR", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 6, goalsAgainst: 3, goalDifference: 3, status: "qualified" },
    { code: "SCO", played: 3, wins: 1, draws: 0, losses: 2, points: 3, goalsFor: 1, goalsAgainst: 4, goalDifference: -3, status: "eliminated" },
    { code: "HAI", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 2, goalsAgainst: 8, goalDifference: -6, status: "eliminated" },
  ],
  D: [
    { code: "USA", played: 3, wins: 2, draws: 0, losses: 1, points: 6, goalsFor: 8, goalsAgainst: 4, goalDifference: 4, status: "qualified" },
    { code: "AUS", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 2, goalsAgainst: 2, goalDifference: 0, status: "qualified" },
    { code: "PAR", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 2, goalsAgainst: 4, goalDifference: -2, status: "thirdQualified" },
    { code: "TUR", played: 3, wins: 1, draws: 0, losses: 2, points: 3, goalsFor: 3, goalsAgainst: 5, goalDifference: -2, status: "eliminated" },
  ],
  E: [
    { code: "GER", played: 3, wins: 2, draws: 0, losses: 1, points: 6, goalsFor: 10, goalsAgainst: 4, goalDifference: 6, status: "qualified" },
    { code: "CIV", played: 3, wins: 2, draws: 0, losses: 1, points: 6, goalsFor: 4, goalsAgainst: 2, goalDifference: 2, status: "qualified" },
    { code: "ECU", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 2, goalsAgainst: 2, goalDifference: 0, status: "thirdQualified" },
    { code: "CUW", played: 3, wins: 0, draws: 1, losses: 2, points: 1, goalsFor: 1, goalsAgainst: 9, goalDifference: -8, status: "eliminated" },
  ],
  F: [
    { code: "NED", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 10, goalsAgainst: 4, goalDifference: 6, status: "qualified" },
    { code: "JPN", played: 3, wins: 1, draws: 2, losses: 0, points: 5, goalsFor: 7, goalsAgainst: 3, goalDifference: 4, status: "qualified" },
    { code: "SWE", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 7, goalsAgainst: 7, goalDifference: 0, status: "thirdQualified" },
    { code: "TUN", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 2, goalsAgainst: 12, goalDifference: -10, status: "eliminated" },
  ],
  G: [
    { code: "BEL", played: 3, wins: 1, draws: 2, losses: 0, points: 5, goalsFor: 6, goalsAgainst: 2, goalDifference: 4, status: "qualified" },
    { code: "EGY", played: 3, wins: 1, draws: 2, losses: 0, points: 5, goalsFor: 5, goalsAgainst: 3, goalDifference: 2, status: "qualified" },
    { code: "IRN", played: 3, wins: 0, draws: 3, losses: 0, points: 3, goalsFor: 3, goalsAgainst: 3, goalDifference: 0, status: "eliminated" },
    { code: "NZL", played: 3, wins: 0, draws: 1, losses: 2, points: 1, goalsFor: 4, goalsAgainst: 10, goalDifference: -6, status: "eliminated" },
  ],
  H: [
    { code: "ESP", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 5, goalsAgainst: 0, goalDifference: 5, status: "qualified" },
    { code: "CPV", played: 3, wins: 0, draws: 3, losses: 0, points: 3, goalsFor: 2, goalsAgainst: 2, goalDifference: 0, status: "qualified" },
    { code: "URU", played: 3, wins: 0, draws: 2, losses: 1, points: 2, goalsFor: 3, goalsAgainst: 4, goalDifference: -1, status: "eliminated" },
    { code: "KSA", played: 3, wins: 0, draws: 2, losses: 1, points: 2, goalsFor: 1, goalsAgainst: 5, goalDifference: -4, status: "eliminated" },
  ],
  I: [
    { code: "FRA", played: 3, wins: 3, draws: 0, losses: 0, points: 9, goalsFor: 10, goalsAgainst: 2, goalDifference: 8, status: "qualified" },
    { code: "NOR", played: 3, wins: 2, draws: 0, losses: 1, points: 6, goalsFor: 8, goalsAgainst: 7, goalDifference: 1, status: "qualified" },
    { code: "SEN", played: 3, wins: 1, draws: 0, losses: 2, points: 3, goalsFor: 8, goalsAgainst: 6, goalDifference: 2, status: "thirdQualified" },
    { code: "IRQ", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 1, goalsAgainst: 12, goalDifference: -11, status: "eliminated" },
  ],
  J: [
    { code: "ARG", played: 3, wins: 3, draws: 0, losses: 0, points: 9, goalsFor: 8, goalsAgainst: 1, goalDifference: 7, status: "qualified" },
    { code: "AUT", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 6, goalsAgainst: 6, goalDifference: 0, status: "qualified" },
    { code: "ALG", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 5, goalsAgainst: 7, goalDifference: -2, status: "thirdQualified" },
    { code: "JOR", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 3, goalsAgainst: 8, goalDifference: -5, status: "eliminated" },
  ],
  K: [
    { code: "COL", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 4, goalsAgainst: 1, goalDifference: 3, status: "qualified" },
    { code: "POR", played: 3, wins: 1, draws: 2, losses: 0, points: 5, goalsFor: 6, goalsAgainst: 1, goalDifference: 5, status: "qualified" },
    { code: "COD", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 4, goalsAgainst: 3, goalDifference: 1, status: "thirdQualified" },
    { code: "UZB", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 2, goalsAgainst: 11, goalDifference: -9, status: "eliminated" },
  ],
  L: [
    { code: "ENG", played: 3, wins: 2, draws: 1, losses: 0, points: 7, goalsFor: 6, goalsAgainst: 2, goalDifference: 4, status: "qualified" },
    { code: "CRO", played: 3, wins: 2, draws: 0, losses: 1, points: 6, goalsFor: 5, goalsAgainst: 5, goalDifference: 0, status: "qualified" },
    { code: "GHA", played: 3, wins: 1, draws: 1, losses: 1, points: 4, goalsFor: 2, goalsAgainst: 2, goalDifference: 0, status: "thirdQualified" },
    { code: "PAN", played: 3, wins: 0, draws: 0, losses: 3, points: 0, goalsFor: 0, goalsAgainst: 4, goalDifference: -4, status: "eliminated" },
  ],
};

export const knockoutFixtures: KnockoutFixture[] = [
  {
    id: "R32-74",
    round: "R32",
    slot: "Match 74 · 32 强 · 点球真实赛果",
    home: "GER",
    away: "PAR",
    status: "actual",
    homeGoals: 1,
    awayGoals: 1,
    winner: "PAR",
    scoreNote: "加时 1-1，点球 3-4",
  },
  {
    id: "R32-77",
    round: "R32",
    slot: "Match 77 · 32 强 · 已完赛",
    home: "FRA",
    away: "SWE",
    status: "actual",
    homeGoals: 3,
    awayGoals: 0,
    winner: "FRA",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-73",
    round: "R32",
    slot: "Match 73 · 32 强 · 已完赛",
    home: "RSA",
    away: "CAN",
    status: "actual",
    homeGoals: 0,
    awayGoals: 1,
    winner: "CAN",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-75",
    round: "R32",
    slot: "Match 75 · 32 强 · 点球真实赛果",
    home: "NED",
    away: "MAR",
    status: "actual",
    homeGoals: 1,
    awayGoals: 1,
    winner: "MAR",
    scoreNote: "加时 1-1，点球 2-3",
  },
  {
    id: "R32-76",
    round: "R32",
    slot: "Match 76 · 32 强 · 已完赛",
    home: "BRA",
    away: "JPN",
    status: "actual",
    homeGoals: 2,
    awayGoals: 1,
    winner: "BRA",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-78",
    round: "R32",
    slot: "Match 78 · 32 强 · 已完赛",
    home: "CIV",
    away: "NOR",
    status: "actual",
    homeGoals: 1,
    awayGoals: 2,
    winner: "NOR",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-79",
    round: "R32",
    slot: "Match 79 · 32 强 · 已完赛",
    home: "MEX",
    away: "ECU",
    status: "actual",
    homeGoals: 2,
    awayGoals: 0,
    winner: "MEX",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-80",
    round: "R32",
    slot: "Match 80 · 32 强 · 已完赛",
    home: "ENG",
    away: "COD",
    status: "actual",
    homeGoals: 2,
    awayGoals: 1,
    winner: "ENG",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-83",
    round: "R32",
    slot: "Match 83 · 32 强 · 已完赛",
    home: "POR",
    away: "CRO",
    status: "actual",
    homeGoals: 2,
    awayGoals: 1,
    winner: "POR",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-84",
    round: "R32",
    slot: "Match 84 · 32 强 · 已完赛",
    home: "ESP",
    away: "AUT",
    status: "actual",
    homeGoals: 3,
    awayGoals: 0,
    winner: "ESP",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-81",
    round: "R32",
    slot: "Match 81 · 32 强 · 已完赛",
    home: "USA",
    away: "BIH",
    status: "actual",
    homeGoals: 2,
    awayGoals: 0,
    winner: "USA",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-82",
    round: "R32",
    slot: "Match 82 · 32 强 · 加时真实赛果",
    home: "BEL",
    away: "SEN",
    status: "actual",
    homeGoals: 3,
    awayGoals: 2,
    winner: "BEL",
    scoreNote: "加时",
  },
  {
    id: "R32-86",
    round: "R32",
    slot: "Match 86 · 32 强 · 加时真实赛果",
    home: "ARG",
    away: "CPV",
    status: "actual",
    homeGoals: 3,
    awayGoals: 2,
    winner: "ARG",
    scoreNote: "加时",
  },
  {
    id: "R32-88",
    round: "R32",
    slot: "Match 88 · 32 强 · 点球真实赛果",
    home: "AUS",
    away: "EGY",
    status: "actual",
    homeGoals: 1,
    awayGoals: 1,
    winner: "EGY",
    scoreNote: "加时 1-1，点球 2-4",
  },
  {
    id: "R32-85",
    round: "R32",
    slot: "Match 85 · 32 强 · 已完赛",
    home: "SUI",
    away: "ALG",
    status: "actual",
    homeGoals: 2,
    awayGoals: 0,
    winner: "SUI",
    scoreNote: "真实赛果",
  },
  {
    id: "R32-87",
    round: "R32",
    slot: "Match 87 · 32 强 · 已完赛",
    home: "COL",
    away: "GHA",
    status: "actual",
    homeGoals: 1,
    awayGoals: 0,
    winner: "COL",
    scoreNote: "真实赛果",
  },
];
