import type { Team, Weights } from "./types";

export const defaultWeights: Weights = {
  strength: 34,
  form: 22,
  depth: 18,
  knockout: 16,
  travel: 10,
};

export const teams: Team[] = [
  {
    code: "MEX",
    name: "墨西哥",
    group: "A",
    confederation: "CONCACAF",
    rank: 14,
    strength: 82,
    form: 76,
    depth: 74,
    knockout: 70,
    travel: 94,
    attack: 78,
    defense: 76,
    note: "东道主之一，旅行适应和主场噪声优势明显，但淘汰赛上限取决于锋线效率。",
  },
  {
    code: "RSA",
    name: "南非",
    group: "A",
    confederation: "CAF",
    rank: 54,
    strength: 66,
    form: 64,
    depth: 58,
    knockout: 54,
    travel: 68,
    attack: 61,
    defense: 63,
    note: "身体对抗和转换速度有冲击力，小组阶段需要从定位球打开局面。",
  },
  {
    code: "KOR",
    name: "韩国",
    group: "A",
    confederation: "AFC",
    rank: 23,
    strength: 76,
    form: 78,
    depth: 70,
    knockout: 64,
    travel: 60,
    attack: 74,
    defense: 71,
    note: "反击和边路推进稳定，核心球员状态会显著影响淘汰赛概率。",
  },
  {
    code: "ITA",
    name: "意大利",
    group: "A",
    confederation: "UEFA",
    rank: 9,
    strength: 86,
    form: 79,
    depth: 82,
    knockout: 89,
    travel: 62,
    attack: 81,
    defense: 86,
    note: "杯赛经验和防守结构优势突出，适合低比分淘汰赛。",
  },
  {
    code: "CAN",
    name: "加拿大",
    group: "B",
    confederation: "CONCACAF",
    rank: 31,
    strength: 75,
    form: 72,
    depth: 68,
    knockout: 58,
    travel: 96,
    attack: 77,
    defense: 69,
    note: "东道主之一，速度与纵深优势明显，防线抗压是上限变量。",
  },
  {
    code: "SUI",
    name: "瑞士",
    group: "B",
    confederation: "UEFA",
    rank: 18,
    strength: 81,
    form: 77,
    depth: 78,
    knockout: 76,
    travel: 63,
    attack: 75,
    defense: 79,
    note: "大赛稳定性好，面对强队时的中场控制和防线纪律是主要资产。",
  },
  {
    code: "EGY",
    name: "埃及",
    group: "B",
    confederation: "CAF",
    rank: 32,
    strength: 74,
    form: 70,
    depth: 66,
    knockout: 66,
    travel: 61,
    attack: 76,
    defense: 70,
    note: "前场个人能力强，小组出线取决于防守转换和核心健康。",
  },
  {
    code: "JPN",
    name: "日本",
    group: "B",
    confederation: "AFC",
    rank: 16,
    strength: 83,
    form: 85,
    depth: 80,
    knockout: 72,
    travel: 58,
    attack: 82,
    defense: 78,
    note: "高压和控传体系成熟，板凳深度近年提升，具备连续爆冷能力。",
  },
  {
    code: "BRA",
    name: "巴西",
    group: "C",
    confederation: "CONMEBOL",
    rank: 5,
    strength: 91,
    form: 82,
    depth: 92,
    knockout: 90,
    travel: 66,
    attack: 92,
    defense: 84,
    note: "进攻天赋和阵容厚度仍是第一梯队，模型担忧点是防守稳定性与临场波动。",
  },
  {
    code: "SCO",
    name: "苏格兰",
    group: "C",
    confederation: "UEFA",
    rank: 33,
    strength: 73,
    form: 70,
    depth: 67,
    knockout: 60,
    travel: 60,
    attack: 68,
    defense: 72,
    note: "对抗强度高，适合低比分缠斗，需要提高禁区内转化率。",
  },
  {
    code: "MAR",
    name: "摩洛哥",
    group: "C",
    confederation: "CAF",
    rank: 12,
    strength: 84,
    form: 82,
    depth: 77,
    knockout: 81,
    travel: 64,
    attack: 78,
    defense: 84,
    note: "上届世界杯证明了防守与转换质量，继续具备淘汰赛韧性。",
  },
  {
    code: "AUS",
    name: "澳大利亚",
    group: "C",
    confederation: "AFC",
    rank: 27,
    strength: 72,
    form: 73,
    depth: 66,
    knockout: 67,
    travel: 55,
    attack: 68,
    defense: 73,
    note: "身体对抗和纪律性强，赛程密集时体能管理是关键。",
  },
  {
    code: "USA",
    name: "美国",
    group: "D",
    confederation: "CONCACAF",
    rank: 11,
    strength: 84,
    form: 78,
    depth: 80,
    knockout: 68,
    travel: 98,
    attack: 82,
    defense: 78,
    note: "东道主红利和年轻阵容速度明显，淘汰赛经验是主要折扣项。",
  },
  {
    code: "POL",
    name: "波兰",
    group: "D",
    confederation: "UEFA",
    rank: 29,
    strength: 74,
    form: 67,
    depth: 68,
    knockout: 64,
    travel: 61,
    attack: 75,
    defense: 69,
    note: "依赖中锋支点和定位球，面对高压球队时出球质量是风险点。",
  },
  {
    code: "SEN",
    name: "塞内加尔",
    group: "D",
    confederation: "CAF",
    rank: 19,
    strength: 80,
    form: 79,
    depth: 74,
    knockout: 72,
    travel: 62,
    attack: 77,
    defense: 80,
    note: "身体素质、防守质量和反击速度均衡，是第二梯队中很难对付的球队。",
  },
  {
    code: "SWE",
    name: "瑞典",
    group: "D",
    confederation: "UEFA",
    rank: 24,
    strength: 77,
    form: 71,
    depth: 72,
    knockout: 70,
    travel: 59,
    attack: 74,
    defense: 76,
    note: "传统高空优势和防守纪律仍在，创造力决定能走多远。",
  },
  {
    code: "GER",
    name: "德国",
    group: "E",
    confederation: "UEFA",
    rank: 4,
    strength: 90,
    form: 86,
    depth: 91,
    knockout: 92,
    travel: 61,
    attack: 89,
    defense: 83,
    note: "中前场人才密度极高，模型把大赛修正后的淘汰赛执行力视为冠军级。",
  },
  {
    code: "ECU",
    name: "厄瓜多尔",
    group: "E",
    confederation: "CONMEBOL",
    rank: 26,
    strength: 77,
    form: 76,
    depth: 70,
    knockout: 63,
    travel: 72,
    attack: 74,
    defense: 75,
    note: "南美对抗强度和海拔型体能储备有优势，年轻球员冲击力强。",
  },
  {
    code: "TUN",
    name: "突尼斯",
    group: "E",
    confederation: "CAF",
    rank: 41,
    strength: 68,
    form: 66,
    depth: 61,
    knockout: 57,
    travel: 63,
    attack: 62,
    defense: 69,
    note: "低位防守和反击有组织性，面对强队时需要早段守住比分。",
  },
  {
    code: "NZL",
    name: "新西兰",
    group: "E",
    confederation: "OFC",
    rank: 88,
    strength: 59,
    form: 58,
    depth: 52,
    knockout: 48,
    travel: 50,
    attack: 55,
    defense: 57,
    note: "身体条件不差，但整体比赛强度和阵容厚度差距较大。",
  },
  {
    code: "ARG",
    name: "阿根廷",
    group: "F",
    confederation: "CONMEBOL",
    rank: 1,
    strength: 93,
    form: 90,
    depth: 88,
    knockout: 96,
    travel: 69,
    attack: 90,
    defense: 86,
    note: "卫冕冠军的稳定心态、淘汰赛经验和中场控制使其仍是模型冠军热门。",
  },
  {
    code: "DEN",
    name: "丹麦",
    group: "F",
    confederation: "UEFA",
    rank: 21,
    strength: 79,
    form: 73,
    depth: 76,
    knockout: 72,
    travel: 60,
    attack: 74,
    defense: 79,
    note: "体系纪律强，防守质量可靠，但缺少高爆点会限制淘汰赛上限。",
  },
  {
    code: "IRN",
    name: "伊朗",
    group: "F",
    confederation: "AFC",
    rank: 20,
    strength: 76,
    form: 75,
    depth: 69,
    knockout: 59,
    travel: 58,
    attack: 72,
    defense: 73,
    note: "亚洲强队，防守和定位球稳定，小组赛抗压能力强于淘汰赛。",
  },
  {
    code: "CRC",
    name: "哥斯达黎加",
    group: "F",
    confederation: "CONCACAF",
    rank: 52,
    strength: 65,
    form: 62,
    depth: 58,
    knockout: 61,
    travel: 78,
    attack: 59,
    defense: 66,
    note: "门将与防守传统仍是基础，进攻端创造力决定能否爆冷。",
  },
  {
    code: "FRA",
    name: "法国",
    group: "G",
    confederation: "UEFA",
    rank: 2,
    strength: 94,
    form: 88,
    depth: 95,
    knockout: 94,
    travel: 62,
    attack: 93,
    defense: 87,
    note: "阵容深度和锋线速度冠绝多数对手，是模型给出的最高冠军概率球队。",
  },
  {
    code: "COL",
    name: "哥伦比亚",
    group: "G",
    confederation: "CONMEBOL",
    rank: 13,
    strength: 83,
    form: 84,
    depth: 77,
    knockout: 73,
    travel: 75,
    attack: 81,
    defense: 78,
    note: "近期状态和南美对抗强度加分，具备进入八强的质量。",
  },
  {
    code: "NGA",
    name: "尼日利亚",
    group: "G",
    confederation: "CAF",
    rank: 28,
    strength: 76,
    form: 71,
    depth: 72,
    knockout: 63,
    travel: 63,
    attack: 79,
    defense: 68,
    note: "锋线冲击力出色，但防守组织和比赛控制仍有波动。",
  },
  {
    code: "KSA",
    name: "沙特",
    group: "G",
    confederation: "AFC",
    rank: 57,
    strength: 64,
    form: 62,
    depth: 59,
    knockout: 55,
    travel: 57,
    attack: 61,
    defense: 62,
    note: "具备单场爆冷基因，但连续高强度赛程下稳定性不足。",
  },
  {
    code: "ESP",
    name: "西班牙",
    group: "H",
    confederation: "UEFA",
    rank: 3,
    strength: 92,
    form: 89,
    depth: 90,
    knockout: 88,
    travel: 61,
    attack: 88,
    defense: 86,
    note: "控球、压迫和年轻化红利明显，若进攻效率稳定就是冠军级。",
  },
  {
    code: "URU",
    name: "乌拉圭",
    group: "H",
    confederation: "CONMEBOL",
    rank: 10,
    strength: 86,
    form: 84,
    depth: 80,
    knockout: 86,
    travel: 72,
    attack: 84,
    defense: 83,
    note: "新老结合、侵略性和淘汰赛气质兼具，模型视为高威胁黑马。",
  },
  {
    code: "GHA",
    name: "加纳",
    group: "H",
    confederation: "CAF",
    rank: 47,
    strength: 70,
    form: 65,
    depth: 66,
    knockout: 62,
    travel: 62,
    attack: 69,
    defense: 66,
    note: "冲击力强但稳定性不足，小组赛需要控制失误率。",
  },
  {
    code: "QAT",
    name: "卡塔尔",
    group: "H",
    confederation: "AFC",
    rank: 35,
    strength: 68,
    form: 67,
    depth: 62,
    knockout: 57,
    travel: 56,
    attack: 64,
    defense: 65,
    note: "亚洲杯经验有帮助，但面对欧美高节奏球队时防线压力偏大。",
  },
  {
    code: "POR",
    name: "葡萄牙",
    group: "I",
    confederation: "UEFA",
    rank: 6,
    strength: 90,
    form: 87,
    depth: 93,
    knockout: 86,
    travel: 62,
    attack: 91,
    defense: 83,
    note: "前场和边路人才密度极高，深度足以支撑长赛程。",
  },
  {
    code: "CIV",
    name: "科特迪瓦",
    group: "I",
    confederation: "CAF",
    rank: 38,
    strength: 73,
    form: 76,
    depth: 70,
    knockout: 66,
    travel: 63,
    attack: 74,
    defense: 70,
    note: "非洲杯冠军气质加分，身体对抗和边路突击有竞争力。",
  },
  {
    code: "PER",
    name: "秘鲁",
    group: "I",
    confederation: "CONMEBOL",
    rank: 40,
    strength: 70,
    form: 66,
    depth: 64,
    knockout: 62,
    travel: 73,
    attack: 65,
    defense: 70,
    note: "南美经验能提高下限，但进攻火力偏弱。",
  },
  {
    code: "CHN",
    name: "中国",
    group: "I",
    confederation: "AFC",
    rank: 79,
    strength: 57,
    form: 55,
    depth: 53,
    knockout: 46,
    travel: 52,
    attack: 52,
    defense: 55,
    note: "模型给出较低出线概率，重点在防守组织和减少非受迫失误。",
  },
  {
    code: "NED",
    name: "荷兰",
    group: "J",
    confederation: "UEFA",
    rank: 7,
    strength: 88,
    form: 84,
    depth: 84,
    knockout: 87,
    travel: 61,
    attack: 84,
    defense: 88,
    note: "中后场质量和淘汰赛经验优秀，若锋线效率稳定可进四强。",
  },
  {
    code: "USA2",
    name: "牙买加",
    group: "J",
    confederation: "CONCACAF",
    rank: 43,
    strength: 70,
    form: 69,
    depth: 65,
    knockout: 57,
    travel: 80,
    attack: 72,
    defense: 64,
    note: "速度和单兵爆点明显，防守结构是能否出线的关键。",
  },
  {
    code: "TUR",
    name: "土耳其",
    group: "J",
    confederation: "UEFA",
    rank: 22,
    strength: 78,
    form: 80,
    depth: 74,
    knockout: 69,
    travel: 60,
    attack: 79,
    defense: 72,
    note: "年轻核心活力强，进攻端创造力足，防守波动带来不确定性。",
  },
  {
    code: "MALI",
    name: "马里",
    group: "J",
    confederation: "CAF",
    rank: 44,
    strength: 69,
    form: 68,
    depth: 64,
    knockout: 58,
    travel: 62,
    attack: 66,
    defense: 69,
    note: "身体条件和中场拦截好，但大赛经验偏少。",
  },
  {
    code: "BEL",
    name: "比利时",
    group: "K",
    confederation: "UEFA",
    rank: 8,
    strength: 87,
    form: 81,
    depth: 82,
    knockout: 80,
    travel: 61,
    attack: 86,
    defense: 79,
    note: "过渡期后仍具备高质量前场，防线速度是关键变量。",
  },
  {
    code: "CHI",
    name: "智利",
    group: "K",
    confederation: "CONMEBOL",
    rank: 39,
    strength: 71,
    form: 65,
    depth: 63,
    knockout: 68,
    travel: 72,
    attack: 67,
    defense: 70,
    note: "经验丰富但年龄结构偏大，连续高节奏比赛压力明显。",
  },
  {
    code: "ALG",
    name: "阿尔及利亚",
    group: "K",
    confederation: "CAF",
    rank: 36,
    strength: 74,
    form: 72,
    depth: 69,
    knockout: 65,
    travel: 63,
    attack: 75,
    defense: 69,
    note: "前场技术与转换速度不错，稳定性决定能否冲击出线。",
  },
  {
    code: "IRQ",
    name: "伊拉克",
    group: "K",
    confederation: "AFC",
    rank: 56,
    strength: 64,
    form: 66,
    depth: 60,
    knockout: 53,
    travel: 56,
    attack: 61,
    defense: 63,
    note: "团队纪律不错，面对强队时需要依赖低位防守和反击效率。",
  },
  {
    code: "ENG",
    name: "英格兰",
    group: "L",
    confederation: "UEFA",
    rank: 4,
    strength: 91,
    form: 86,
    depth: 92,
    knockout: 84,
    travel: 60,
    attack: 90,
    defense: 84,
    note: "阵容深度和定位球质量极高，模型仍对关键战临场保守度做折扣。",
  },
  {
    code: "CRO",
    name: "克罗地亚",
    group: "L",
    confederation: "UEFA",
    rank: 15,
    strength: 82,
    form: 77,
    depth: 75,
    knockout: 91,
    travel: 60,
    attack: 76,
    defense: 81,
    note: "淘汰赛经验巨大加分，但年龄结构和强度延续性是风险。",
  },
  {
    code: "PAN",
    name: "巴拿马",
    group: "L",
    confederation: "CONCACAF",
    rank: 45,
    strength: 68,
    form: 69,
    depth: 61,
    knockout: 54,
    travel: 82,
    attack: 65,
    defense: 66,
    note: "区域适应好，强对抗下仍需提升控球出球。",
  },
  {
    code: "UAE",
    name: "阿联酋",
    group: "L",
    confederation: "AFC",
    rank: 65,
    strength: 62,
    form: 64,
    depth: 58,
    knockout: 51,
    travel: 55,
    attack: 60,
    defense: 60,
    note: "技术型打法面对高压时有风险，出线需要爆冷。",
  },
];
